name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - name: Install bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: "package.json"

    - name: Install dependencies
      shell: bash
      run: bun install
